package alfianwardyanto_171011400038_uas;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wardyanto
 */
public class siswa_alfian extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.getKoneksi();


    /**
     * Creates new form siswa_alfian
     */
    public siswa_alfian() {
        initComponents();
        judul();
        reset();
        tampilData();
        
        //rata kiri kanan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 3);
    }
    
    public void tampilData()    {
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("select * from tb_siswa");
            while (rs.next()){
                Object[] data = {
                    rs.getString("nis"),
                    rs.getString("nama"),
                    rs.getString("jkelamin"),
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void judul(){
        Object[] judul = {"NIS","Nama","J. Kelamin"};
        tabModel = new DefaultTableModel(null, judul);
        tabel.setModel(tabModel);
    }
    
    public void reset(){
        nis_alfian.setText("");
        nama_alfian.setText("");
        bgk.clearSelection();
        edit_alfian.setEnabled(false);
        hapus_alfian.setEnabled(false);
        simpan_alfian.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgk = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nis_alfian = new javax.swing.JTextField();
        nama_alfian = new javax.swing.JTextField();
        P = new javax.swing.JRadioButton();
        W = new javax.swing.JRadioButton();
        simpan_alfian = new javax.swing.JButton();
        edit_alfian = new javax.swing.JButton();
        hapus_alfian = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        kembali_alfian = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIS");

        jLabel2.setText("NAMA");

        jLabel3.setText("Jenis Kelamin");

        bgk.add(P);
        P.setText("Pria");

        bgk.add(W);
        W.setText("Wanita");

        simpan_alfian.setText("SIMPAN");
        simpan_alfian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_alfianActionPerformed(evt);
            }
        });

        edit_alfian.setText("EDIT");
        edit_alfian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_alfianActionPerformed(evt);
            }
        });

        hapus_alfian.setText("HAPUS");
        hapus_alfian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_alfianActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        kembali_alfian.setText("KEMBALI");
        kembali_alfian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_alfianActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("SISWA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nis_alfian, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(nama_alfian))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(simpan_alfian)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edit_alfian))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hapus_alfian)
                                        .addGap(18, 18, 18)
                                        .addComponent(kembali_alfian))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(P)
                                    .addGap(18, 18, 18)
                                    .addComponent(W)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nis_alfian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan_alfian)
                    .addComponent(edit_alfian))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_alfian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus_alfian)
                    .addComponent(kembali_alfian))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(P)
                    .addComponent(W))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_alfianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_alfianActionPerformed
        // TODO add your handling code here:
        if(nis_alfian.getText().equals("") || nama_alfian.getText().equals("") || bgk.getSelection().equals("")){
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap!");
        }else{
        try{
            String jk;
            if(P.isSelected()){
                jk = "Pria";
            }else{
                jk = "Wanita";
            }
            st = cn.createStatement();
            st.executeUpdate("insert into tb_siswa set nis='" + nis_alfian.getText() +"', nama='" + nama_alfian.getText() +"', jkelamin='" + jk+ "', ket='belum'");
            tampilData();
            reset();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
        }catch(Exception e){
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_simpan_alfianActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        simpan_alfian.setEnabled(false);
        edit_alfian.setEnabled(true);
        hapus_alfian.setEnabled(true);
        nis_alfian.setText(tabModel.getValueAt(tabel.getSelectedRow(), 0) + "");
        nama_alfian.setText(tabModel.getValueAt(tabel.getSelectedRow(), 1) + "");
        String a = (tabModel.getValueAt(tabel.getSelectedRow(), 2) + "");
        if(a.equals("P")){
            P.setSelected(true);
        }else{
            W.setSelected(true);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void edit_alfianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_alfianActionPerformed
        // TODO add your handling code here:
        try{
            simpan_alfian.setEnabled(true);
            String jk;
            if(P.isSelected()){
                jk = "Pria";
            }else{
                jk = "Wanita";
            }
            st = cn.createStatement();
            st.executeUpdate("update tb_siswa set nama='" + nama_alfian.getText() +"', jkelamin='" + jk+ "' where nis='"+ nis_alfian.getText() +"'");
            tampilData();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
            reset();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_edit_alfianActionPerformed

    private void hapus_alfianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_alfianActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            if((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0 ){
                st = cn.createStatement();
                st.executeUpdate("delete from tb_siswa where nis='" + nis_alfian.getText() + "'");
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                tampilData();
                reset();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_hapus_alfianActionPerformed

    private void kembali_alfianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_alfianActionPerformed
        // TODO add your handling code here:
        new home_alfian().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembali_alfianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siswa_alfian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siswa_alfian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siswa_alfian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswa_alfian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siswa_alfian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton P;
    private javax.swing.JRadioButton W;
    private javax.swing.ButtonGroup bgk;
    private javax.swing.JButton edit_alfian;
    private javax.swing.JButton hapus_alfian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali_alfian;
    private javax.swing.JTextField nama_alfian;
    private javax.swing.JTextField nis_alfian;
    private javax.swing.JButton simpan_alfian;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
